version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
  - package_manager: 'python'
    directory: '/'
    update_schedule: 'monthly'
    ignored_updates:
      - match:
          dependency_name: '*'
